import type { Metadata } from "next";
import Header from "@/components/common/headers/Header";
import MainSideBar from "@/components/common/sidebars/MainSideBar";
import { buttonVariants } from "@/components/ui/button";
import { familySideBarlink } from "@/data/Static";
import { MdAdd } from "react-icons/md";
import Link from "next/link";

export const metadata: Metadata = {
  title: "all my family",
  description: "Generated by my family",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <Header />
    <MainSideBar>
    {familySideBarlink?.map((item, index) => (
            <Link href={item.link} key={item.title}>
              <div className="flex items-center gap-4 px-4 py-2 rounded-xl w-auto hover:bg-BG-4 mb-1 cursor-pointer">
                <div className="text-xl leading-loose">{item?.icons}</div>
                <h1 className="font-sans font-600">{item?.title}</h1>
              </div>
            </Link>
          ))}
           <div className="action-part mt-5">
        <Link
          href={"/family/create"}
          className={buttonVariants({
            className: "gap-1 p-2 bg-BG-4 w-full font-600  mb-6",
          })}
        >
          <MdAdd /> Create Family
        </Link>
      </div>
    </MainSideBar>
    <main className="xxl:ml-side  xl:ml-side-sm p-2.5 h-[calc(100vh-var(--m-top))] mt-top-custom">
    {children} 
    </main>
  </>
  );
}
